defaults:
  - model: GAE
  - dataset: synthetic
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

seed: 17
seed_data: 11
epochs: 1000
exp_group: "new"

optimizer:
  lr: 1e-3
  weight_decay: 1e-5
  early_stop: True
  early_stop_iters: 40
  min_iters: 20
