defaults:
  - model: Diffusion
  - dataset: hetero
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

seed: 17
seed_data: 11
epochs: 2000
log_epoch: 10
exp_group: "new"
enable_profiler: False

optimizer:
  lr: 8e-3
  weight_decay: 1e-5
  early_stop: True
  early_stop_iters: 100
  min_iters: 200
