defaults:
  - model: GAE
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

seed: 17
epochs: 300

optimizer:
  lr: 1e-3
  weight_decay: 1e-5
  early_stop: True
  early_stop_iters: 40

dataset:
  # "Synthetic", "Cora", "Citeseer", "PubMed", "Movielens1M", "Movielens100K"
  name: Movielens100K
  test_size: 0.1
  # used for Synthetic dataset only:
  ndata: 500
  dimx: 20
